version: '3.8'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"  # Map host port 5001 to container port 80
    volumes:
      - .:/usr/share/nginx/html
    restart: unless-stopped
